# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI
on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: tree-sitter/setup-action@v2
      - run: tree-sitter generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate parser"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - generate
    steps:
      - uses: actions/checkout@v3
      - uses: tree-sitter/setup-action@v2
      - run: tree-sitter test
